sudo: required
services:
  - docker

before_install:
  - docker build -t vivekcdp/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run vivekcdp/react-test npm test -- --coverage

after_sucess:
  - docker build -t vivekcdp/multi-client ./client
  - docker build -t vivekcdp/multi-nginx ./nginx
  - docker build -t vivekcdp/multi-server ./server
  - docker build -t vivekcdp/mutli-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # echo will fetch the docker password from environment variables and make it available as stdin for next command which is docker login her
  # Push this image into our docker hub account
  - docker push vivekcdp/multi-client
  - docker push vivekcdp/multi-nginx
  - docker push vivekcdp/multi-server
  - docker push vivekcdp/mutli-worker